CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(25) NOT NULL UNIQUE,
  password TEXT NOT NULL,
  is_admin BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE cards (
  id SERIAL PRIMARY KEY,
  word VARCHAR(25) NOT NULL,
  defn TEXT NOT NULL,
  bin INTEGER NOT NULL,
  wrongs INTEGER NOT NULL,
  due TIMESTAMP NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users
);